В JavaScript исключения (ошибки) обрабатываются с помощью конструкции `try...catch`. Эта конструкция позволяет отслеживать ошибки и выполнять определенные действия в случае их возникновения. Вот основная структура конструкции `try...catch`:

```javascript
try {
  // Код, который может вызывать ошибки
} catch (error) {
  // Обработка ошибки
}
```

Код, который может вызывать ошибки, помещается в блок `try`. Если во время выполнения этого кода возникает ошибка, выполнение переходит в блок `catch`. В блоке `catch` указывается переменная `error`, которая содержит информацию об ошибке.

Пример использования `try...catch`:

```javascript
try {
  // Код, который может вызывать ошибки
  const result = 10 / 0; // Деление на ноль вызывает ошибку
} catch (error) {
  // Обработка ошибки
  console.log('Произошла ошибка:', error);
}
```

В приведенном примере, деление на ноль вызывает ошибку, и выполнение кода переходит в блок `catch`. В блоке `catch` мы можем определить, как обрабатывать ошибку. В данном случае, мы выводим сообщение об ошибке в консоль.

Конструкцию `try...catch` можно использовать для обработки различных типов ошибок, включая встроенные ошибки JavaScript или созданные пользователем ошибки. Можно также использовать дополнительные блоки `catch`, чтобы обработать разные типы ошибок по-разному.

```javascript
try {
  // Код, который может вызывать ошибки
} catch (error1) {
  // Обработка первого типа ошибки
} catch (error2) {
  // Обработка второго типа ошибки
} finally {
  // Код, который выполняется в любом случае
}
```

Блок `finally` является необязательным и содержит код, который будет выполнен в любом случае, независимо от того, была ошибка или нет.

Обработка ошибок с помощью `try...catch` является мощным инструментом для управления исключительными ситуациями и обеспечения более плавного выполнения кода. Она позволяет перехватывать ошибки, делать соответствующие действия и предоставлять информацию о возникших проблемах.